// Package repository provides database models.
//
// Code generated by github.com/kukymbr/dbmodgen DO NOT EDIT.
// Generator version: unknown (revision unknown, built at 20250918000000)
package repository

import (
	"github.com/google/uuid"

	"time"
)

type User struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Email     string    `db:"email" json:"email"`
	Name      *string   `db:"name" json:"name"`
	Password  string    `db:"password" json:"password"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
