// Package {{ .Package }} provides structured SQL queries.
//
// Code generated by github.com/kukymbr/dbmodgen DO NOT EDIT.
// Sqlamble version: {{ .Version }}
// Source: {{ .SourcePath }}
package {{ .Package }}

