// Package {{ .Package }} provides database models.
//
// Code generated by github.com/kukymbr/dbmodgen DO NOT EDIT.
// Generator version: {{ .Version }}
package {{.Package}}

{{if .HasImports}}
import (
    {{range .Imports}}
    "{{.}}"
    {{end}}
)
{{end}}

{{range $model := .Entities}}
type {{.GoName}} struct {
	{{range .Columns}}
	    {{.GoName}} {{.Type}} {{.Tag}} {{.Comment}}{{end}}
	{{if .HasRelations}}
        {{range .Relations}}
            {{.GoName}} *{{.GoType}} {{.Tag}} {{.Comment}}
        {{end}}
	{{end}}
}
{{end}}